version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Create conda environment
          command: |
            conda env create -f environment.yml
      - run:
          name: Running tests
          command: |
            source activate circle-ci
            python tests.py > artifact.txt
      - store_artifacts:
          path: artifact.txt
          destination: demo-circleci-conda